import React, { useState } from 'react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../lib/auth';
import { Lock, CheckCircle, AlertCircle, Loader2 } from 'lucide-react';

export default function TwoFactorSetup() {
    const { user } = useAuth();
    const [loading, setLoading] = useState(false);
    const [qrCode, setQrCode] = useState<string | null>(null);
    const [secret, setSecret] = useState<string | null>(null);
    const [verifyCode, setVerifyCode] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState(false);

    const init2FA = async () => {
        setLoading(true);
        setError(null);
        try {
            const { data, error } = await supabase.auth.mfa.enroll({
                factorType: 'totp',
            });
            if (error) throw error;

            if (data.type === 'totp') {
                setQrCode(data.totp.qr_code);
                setSecret(data.id); // This is the factor ID needed for verification
            }
        } catch (err: any) {
            setError(err.message || 'Failed to initialize 2FA');
        } finally {
            setLoading(false);
        }
    };

    const verifyAndEnable = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!secret || !verifyCode) return;

        setLoading(true);
        setError(null);

        try {
            const { data: challengeData, error: challengeError } = await supabase.auth.mfa.challenge({ factorId: secret });
            if (challengeError) throw challengeError;

            const { data, error } = await supabase.auth.mfa.verify({
                factorId: secret,
                challengeId: challengeData.id,
                code: verifyCode
            });

            if (error) throw error;
            setSuccess(true);
        } catch (err: any) {
            setError(err.message || 'Invalid verification code');
        } finally {
            setLoading(false);
        }
    };

    if (!user) return null;

    return (
        <div className="bg-white/[0.03] border border-white/10 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-6">
                <Lock size={18} className="text-red-400" />
                <h3 className="font-black uppercase tracking-widest text-[11px] text-white/60">
                    Two-Factor Authentication
                </h3>
            </div>

            {success ? (
                <div className="flex items-center gap-2 p-4 bg-green-500/10 border border-green-500/20 rounded-xl text-xs text-green-400 font-mono">
                    <CheckCircle size={16} />
                    2FA has been successfully enabled for your account.
                </div>
            ) : (
                <div className="space-y-6">
                    <p className="text-xs text-white/50 leading-relaxed">
                        Enhance your account security by enabling two-factor authentication (2FA). This will require a code from your authenticator app (like Google Authenticator or Authy) when you sign in.
                    </p>

                    {error && (
                        <div className="flex items-center gap-2 p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-[10px] text-red-400 font-mono">
                            <AlertCircle size={14} />
                            {error}
                        </div>
                    )}

                    {!qrCode ? (
                        <button
                            onClick={init2FA}
                            disabled={loading}
                            className="flex items-center justify-center gap-2 px-4 py-2.5 bg-white/10 hover:bg-white/20 disabled:opacity-50 text-white rounded-xl text-xs font-bold transition-colors"
                        >
                            {loading && <Loader2 size={14} className="animate-spin" />}
                            Setup Authenticator App
                        </button>
                    ) : (
                        <div className="space-y-6 p-4 bg-black/40 border border-white/5 rounded-xl">
                            <div className="flex flex-col md:flex-row gap-6 items-center">
                                <div className="bg-white p-2 text-black" dangerouslySetInnerHTML={{ __html: qrCode }} />
                                <div className="flex-1 space-y-4">
                                    <p className="text-xs text-white/70">
                                        1. Scan this QR code with your authenticator app.
                                    </p>
                                    <p className="text-xs text-white/70">
                                        2. Enter the 6-digit code generated by the app to verify setup.
                                    </p>

                                    <form onSubmit={verifyAndEnable} className="flex flex-col gap-3">
                                        <input
                                            type="text"
                                            value={verifyCode}
                                            onChange={(e) => setVerifyCode(e.target.value)}
                                            placeholder="000000"
                                            maxLength={6}
                                            className="w-full sm:w-48 bg-white/5 border border-white/10 rounded-xl px-4 py-2 font-mono text-center text-xl tracking-[0.5em] focus:outline-none focus:border-red-500/50 transition-colors"
                                        />
                                        <button
                                            type="submit"
                                            disabled={loading || verifyCode.length !== 6}
                                            className="w-full sm:w-48 flex items-center justify-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-500 disabled:opacity-30 text-white rounded-xl text-xs font-black uppercase tracking-wider transition-colors"
                                        >
                                            {loading && <Loader2 size={14} className="animate-spin" />}
                                            Verify & Enable
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}
